<a href="https://colab.research.google.com/github/bilenyavuz/hello_pytorch/blob/main/pytourch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# prompt: import pytourch and create a scalar tensor

import torch
print(torch.__version__)
# Create a scalar tensor.
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())


2.4.0+cu121
tensor(7)
0
7


In [2]:
# check gpu
!nvidia-smi

Tue Sep 10 18:01:08 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
# prompt: create a vector tensor

# Create a vector tensor.
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)


tensor([7, 7])
1
torch.Size([2])


In [4]:
# prompt: create a matrix tensor

# Create a matrix tensor.
matrix = torch.tensor([[7, 8],
                       [9, 10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)


tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [8]:
# prompt: create a random tensor

# Create a random tensor.
random_tensor = torch.rand(size=(3, 4,5))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)
print(random_tensor.dtype)
random_tensor[0]

tensor([[[0.3265, 0.4224, 0.7577, 0.5254, 0.7612],
         [0.4139, 0.9001, 0.7667, 0.2361, 0.3375],
         [0.4205, 0.7140, 0.0234, 0.7997, 0.2843],
         [0.8309, 0.3662, 0.7734, 0.7558, 0.8443]],

        [[0.0823, 0.3020, 0.5010, 0.3164, 0.3775],
         [0.5746, 0.3739, 0.9517, 0.8857, 0.5742],
         [0.2089, 0.5206, 0.8566, 0.7783, 0.0796],
         [0.3556, 0.2406, 0.2272, 0.1156, 0.0529]],

        [[0.9020, 0.2748, 0.6101, 0.9311, 0.9688],
         [0.3015, 0.2287, 0.4496, 0.3556, 0.0370],
         [0.2576, 0.9154, 0.4163, 0.9856, 0.1139],
         [0.7797, 0.8814, 0.0142, 0.4668, 0.9785]]])
3
torch.Size([3, 4, 5])
torch.float32


tensor([[0.3265, 0.4224, 0.7577, 0.5254, 0.7612],
        [0.4139, 0.9001, 0.7667, 0.2361, 0.3375],
        [0.4205, 0.7140, 0.0234, 0.7997, 0.2843],
        [0.8309, 0.3662, 0.7734, 0.7558, 0.8443]])

In [7]:
# prompt: create a random tensor with zeros

# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros.dtype)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


In [10]:
# prompt: create a range tensor from zero to ten with data type float16

# Create a range tensor.
tensor = torch.arange(start=0, end=10, dtype=torch.float16)
print(tensor)
print(tensor.dtype)


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)
torch.float16


In [13]:
# prompt: create a random tensor for an image with 512x512 size, print details of image tensor

# Create a random tensor for an image with 512x512 size.
image_tensor = torch.rand(size=(512, 512, 3))  # 3 channels for RGB
print(image_tensor)
print(image_tensor.ndim)
print(image_tensor.shape)
print(image_tensor.dtype)


tensor([[[0.7059, 0.8815, 0.1464],
         [0.1403, 0.5003, 0.6423],
         [0.1608, 0.6500, 0.7484],
         ...,
         [0.7840, 0.9710, 0.3940],
         [0.1244, 0.0427, 0.5370],
         [0.0865, 0.7012, 0.6185]],

        [[0.6402, 0.5654, 0.7690],
         [0.6621, 0.3111, 0.9558],
         [0.2733, 0.7357, 0.3050],
         ...,
         [0.7205, 0.1300, 0.7103],
         [0.7400, 0.3764, 0.3872],
         [0.8951, 0.1101, 0.8302]],

        [[0.6328, 0.0793, 0.1930],
         [0.2202, 0.3472, 0.7540],
         [0.5396, 0.4189, 0.0791],
         ...,
         [0.0134, 0.6301, 0.8722],
         [0.9876, 0.0051, 0.6613],
         [0.9011, 0.3734, 0.4785]],

        ...,

        [[0.3112, 0.8531, 0.4414],
         [0.4092, 0.8075, 0.9110],
         [0.5711, 0.5953, 0.7324],
         ...,
         [0.4370, 0.1738, 0.1547],
         [0.2329, 0.6599, 0.6866],
         [0.6130, 0.2094, 0.5038]],

        [[0.8289, 0.7980, 0.7830],
         [0.0436, 0.6861, 0.3911],
         [0.