<a href="https://colab.research.google.com/github/bilenyavuz/hello_pytorch/blob/main/pytourch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: import pytourch and create a scalar tensor

import torch
print(torch.__version__)
# Create a scalar tensor.
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())


2.4.0+cu121
tensor(7)
0
7


In [ ]:
# prompt: create a vector tensor

# Create a vector tensor.
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)


tensor([7, 7])
1
torch.Size([2])


In [ ]:
# prompt: create a matrix tensor

# Create a matrix tensor.
matrix = torch.tensor([[7, 8],
                       [9, 10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)


tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [ ]:
# prompt: create a random tensor

# Create a random tensor.
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)


tensor([[0.6032, 0.1224, 0.3681, 0.6967],
        [0.5557, 0.4702, 0.3322, 0.1136],
        [0.0243, 0.0227, 0.0621, 0.4292]])
2
torch.Size([3, 4])
